package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccountPreferencesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPreferencesAllPropertiesEquals(AccountPreferences expected, AccountPreferences actual) {
        assertAccountPreferencesAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountPreferencesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPreferencesAllUpdatablePropertiesEquals(AccountPreferences expected, AccountPreferences actual) {
        assertAccountPreferencesUpdatableFieldsEquals(expected, actual);
        assertAccountPreferencesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPreferencesAutoGeneratedPropertiesEquals(AccountPreferences expected, AccountPreferences actual) {
        assertThat(actual)
            .as("Verify AccountPreferences auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPreferencesUpdatableFieldsEquals(AccountPreferences expected, AccountPreferences actual) {
        assertThat(actual)
            .as("Verify AccountPreferences relevant properties")
            .satisfies(a -> assertThat(a.getDiscoverable()).as("check discoverable").isEqualTo(expected.getDiscoverable()))
            .satisfies(a -> assertThat(a.getShowCity()).as("check showCity").isEqualTo(expected.getShowCity()))
            .satisfies(a ->
                assertThat(a.getShowFollowConnections()).as("check showFollowConnections").isEqualTo(expected.getShowFollowConnections())
            )
            .satisfies(a -> assertThat(a.getAllowFollows()).as("check allowFollows").isEqualTo(expected.getAllowFollows()))
            .satisfies(a ->
                assertThat(a.getRequireFollowApproval()).as("check requireFollowApproval").isEqualTo(expected.getRequireFollowApproval())
            )
            .satisfies(a -> assertThat(a.getAllowMessagesFrom()).as("check allowMessagesFrom").isEqualTo(expected.getAllowMessagesFrom()))
            .satisfies(a -> assertThat(a.getNotifyEvents()).as("check notifyEvents").isEqualTo(expected.getNotifyEvents()))
            .satisfies(a -> assertThat(a.getNotifyCommunities()).as("check notifyCommunities").isEqualTo(expected.getNotifyCommunities()))
            .satisfies(a -> assertThat(a.getNotifySocial()).as("check notifySocial").isEqualTo(expected.getNotifySocial()))
            .satisfies(a -> assertThat(a.getNotifyAdvantages()).as("check notifyAdvantages").isEqualTo(expected.getNotifyAdvantages()))
            .satisfies(a -> assertThat(a.getNotifySystem()).as("check notifySystem").isEqualTo(expected.getNotifySystem()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPreferencesUpdatableRelationshipsEquals(AccountPreferences expected, AccountPreferences actual) {
        assertThat(actual)
            .as("Verify AccountPreferences relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }
}
