package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AiUsageLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiUsageLogAllPropertiesEquals(AiUsageLog expected, AiUsageLog actual) {
        assertAiUsageLogAutoGeneratedPropertiesEquals(expected, actual);
        assertAiUsageLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiUsageLogAllUpdatablePropertiesEquals(AiUsageLog expected, AiUsageLog actual) {
        assertAiUsageLogUpdatableFieldsEquals(expected, actual);
        assertAiUsageLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiUsageLogAutoGeneratedPropertiesEquals(AiUsageLog expected, AiUsageLog actual) {
        assertThat(actual)
            .as("Verify AiUsageLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiUsageLogUpdatableFieldsEquals(AiUsageLog expected, AiUsageLog actual) {
        assertThat(actual)
            .as("Verify AiUsageLog relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiUsageLogUpdatableRelationshipsEquals(AiUsageLog expected, AiUsageLog actual) {
        assertThat(actual)
            .as("Verify AiUsageLog relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
