package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CityEventSyncLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventSyncLogAllPropertiesEquals(CityEventSyncLog expected, CityEventSyncLog actual) {
        assertCityEventSyncLogAutoGeneratedPropertiesEquals(expected, actual);
        assertCityEventSyncLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventSyncLogAllUpdatablePropertiesEquals(CityEventSyncLog expected, CityEventSyncLog actual) {
        assertCityEventSyncLogUpdatableFieldsEquals(expected, actual);
        assertCityEventSyncLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventSyncLogAutoGeneratedPropertiesEquals(CityEventSyncLog expected, CityEventSyncLog actual) {
        assertThat(actual)
            .as("Verify CityEventSyncLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventSyncLogUpdatableFieldsEquals(CityEventSyncLog expected, CityEventSyncLog actual) {
        assertThat(actual)
            .as("Verify CityEventSyncLog relevant properties")
            .satisfies(a -> assertThat(a.getProviderCode()).as("check providerCode").isEqualTo(expected.getProviderCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getImportedCount()).as("check importedCount").isEqualTo(expected.getImportedCount()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getFinishedAt()).as("check finishedAt").isEqualTo(expected.getFinishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventSyncLogUpdatableRelationshipsEquals(CityEventSyncLog expected, CityEventSyncLog actual) {
        // empty method
    }
}
