package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CityEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventAllPropertiesEquals(CityEvent expected, CityEvent actual) {
        assertCityEventAutoGeneratedPropertiesEquals(expected, actual);
        assertCityEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventAllUpdatablePropertiesEquals(CityEvent expected, CityEvent actual) {
        assertCityEventUpdatableFieldsEquals(expected, actual);
        assertCityEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventAutoGeneratedPropertiesEquals(CityEvent expected, CityEvent actual) {
        assertThat(actual)
            .as("Verify CityEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventUpdatableFieldsEquals(CityEvent expected, CityEvent actual) {
        assertThat(actual)
            .as("Verify CityEvent relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getVenueName()).as("check venueName").isEqualTo(expected.getVenueName()))
            .satisfies(a -> assertThat(a.getAddressText()).as("check addressText").isEqualTo(expected.getAddressText()))
            .satisfies(a -> assertThat(a.getStartsAt()).as("check startsAt").isEqualTo(expected.getStartsAt()))
            .satisfies(a -> assertThat(a.getEndsAt()).as("check endsAt").isEqualTo(expected.getEndsAt()))
            .satisfies(a -> assertThat(a.getCoverImageUrl()).as("check coverImageUrl").isEqualTo(expected.getCoverImageUrl()))
            .satisfies(a -> assertThat(a.getPriceLabel()).as("check priceLabel").isEqualTo(expected.getPriceLabel()))
            .satisfies(a -> assertThat(a.getSourceName()).as("check sourceName").isEqualTo(expected.getSourceName()))
            .satisfies(a -> assertThat(a.getSourceUrl()).as("check sourceUrl").isEqualTo(expected.getSourceUrl()))
            .satisfies(a -> assertThat(a.getTicketUrl()).as("check ticketUrl").isEqualTo(expected.getTicketUrl()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getProviderCode()).as("check providerCode").isEqualTo(expected.getProviderCode()))
            .satisfies(a -> assertThat(a.getExternalId()).as("check externalId").isEqualTo(expected.getExternalId()))
            .satisfies(a -> assertThat(a.getLastSyncedAt()).as("check lastSyncedAt").isEqualTo(expected.getLastSyncedAt()))
            .satisfies(a -> assertThat(a.getRawPayload()).as("check rawPayload").isEqualTo(expected.getRawPayload()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventUpdatableRelationshipsEquals(CityEvent expected, CityEvent actual) {
        // empty method
    }
}
