package com.bialem.backend.domain;

import static com.bialem.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CityEventTicketOfferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventTicketOfferAllPropertiesEquals(CityEventTicketOffer expected, CityEventTicketOffer actual) {
        assertCityEventTicketOfferAutoGeneratedPropertiesEquals(expected, actual);
        assertCityEventTicketOfferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventTicketOfferAllUpdatablePropertiesEquals(CityEventTicketOffer expected, CityEventTicketOffer actual) {
        assertCityEventTicketOfferUpdatableFieldsEquals(expected, actual);
        assertCityEventTicketOfferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventTicketOfferAutoGeneratedPropertiesEquals(CityEventTicketOffer expected, CityEventTicketOffer actual) {
        assertThat(actual)
            .as("Verify CityEventTicketOffer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventTicketOfferUpdatableFieldsEquals(CityEventTicketOffer expected, CityEventTicketOffer actual) {
        assertThat(actual)
            .as("Verify CityEventTicketOffer relevant properties")
            .satisfies(a -> assertThat(a.getProviderCode()).as("check providerCode").isEqualTo(expected.getProviderCode()))
            .satisfies(a -> assertThat(a.getExternalOfferId()).as("check externalOfferId").isEqualTo(expected.getExternalOfferId()))
            .satisfies(a -> assertThat(a.getSellerName()).as("check sellerName").isEqualTo(expected.getSellerName()))
            .satisfies(a -> assertThat(a.getPurchaseUrl()).as("check purchaseUrl").isEqualTo(expected.getPurchaseUrl()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a ->
                assertThat(a.getMinPrice()).as("check minPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMinPrice())
            )
            .satisfies(a ->
                assertThat(a.getMaxPrice()).as("check maxPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMaxPrice())
            )
            .satisfies(a -> assertThat(a.getPriceLabel()).as("check priceLabel").isEqualTo(expected.getPriceLabel()))
            .satisfies(a -> assertThat(a.getAvailability()).as("check availability").isEqualTo(expected.getAvailability()))
            .satisfies(a -> assertThat(a.getFeesIncluded()).as("check feesIncluded").isEqualTo(expected.getFeesIncluded()))
            .satisfies(a -> assertThat(a.getIsOfficial()).as("check isOfficial").isEqualTo(expected.getIsOfficial()))
            .satisfies(a -> assertThat(a.getLastCheckedAt()).as("check lastCheckedAt").isEqualTo(expected.getLastCheckedAt()))
            .satisfies(a -> assertThat(a.getRawPayload()).as("check rawPayload").isEqualTo(expected.getRawPayload()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventTicketOfferUpdatableRelationshipsEquals(CityEventTicketOffer expected, CityEventTicketOffer actual) {
        assertThat(actual)
            .as("Verify CityEventTicketOffer relationships")
            .satisfies(a -> assertThat(a.getCityEvent()).as("check cityEvent").isEqualTo(expected.getCityEvent()));
    }
}
