package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CityEventInterestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventInterestAllPropertiesEquals(CityEventInterest expected, CityEventInterest actual) {
        assertCityEventInterestAutoGeneratedPropertiesEquals(expected, actual);
        assertCityEventInterestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventInterestAllUpdatablePropertiesEquals(CityEventInterest expected, CityEventInterest actual) {
        assertCityEventInterestUpdatableFieldsEquals(expected, actual);
        assertCityEventInterestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventInterestAutoGeneratedPropertiesEquals(CityEventInterest expected, CityEventInterest actual) {
        assertThat(actual)
            .as("Verify CityEventInterest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventInterestUpdatableFieldsEquals(CityEventInterest expected, CityEventInterest actual) {
        assertThat(actual)
            .as("Verify CityEventInterest relevant properties")
            .satisfies(a -> assertThat(a.getLookingForCompany()).as("check lookingForCompany").isEqualTo(expected.getLookingForCompany()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityEventInterestUpdatableRelationshipsEquals(CityEventInterest expected, CityEventInterest actual) {
        assertThat(actual)
            .as("Verify CityEventInterest relationships")
            .satisfies(a -> assertThat(a.getCityEvent()).as("check cityEvent").isEqualTo(expected.getCityEvent()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
