package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityMemberAllPropertiesEquals(CommunityMember expected, CommunityMember actual) {
        assertCommunityMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityMemberAllUpdatablePropertiesEquals(CommunityMember expected, CommunityMember actual) {
        assertCommunityMemberUpdatableFieldsEquals(expected, actual);
        assertCommunityMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityMemberAutoGeneratedPropertiesEquals(CommunityMember expected, CommunityMember actual) {
        assertThat(actual)
            .as("Verify CommunityMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityMemberUpdatableFieldsEquals(CommunityMember expected, CommunityMember actual) {
        assertThat(actual)
            .as("Verify CommunityMember relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityMemberUpdatableRelationshipsEquals(CommunityMember expected, CommunityMember actual) {
        assertThat(actual)
            .as("Verify CommunityMember relationships")
            .satisfies(a -> assertThat(a.getCommunity()).as("check community").isEqualTo(expected.getCommunity()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
