package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityModeratorAssistantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityModeratorAssistantAllPropertiesEquals(
        CommunityModeratorAssistant expected,
        CommunityModeratorAssistant actual
    ) {
        assertCommunityModeratorAssistantAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityModeratorAssistantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityModeratorAssistantAllUpdatablePropertiesEquals(
        CommunityModeratorAssistant expected,
        CommunityModeratorAssistant actual
    ) {
        assertCommunityModeratorAssistantUpdatableFieldsEquals(expected, actual);
        assertCommunityModeratorAssistantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityModeratorAssistantAutoGeneratedPropertiesEquals(
        CommunityModeratorAssistant expected,
        CommunityModeratorAssistant actual
    ) {
        assertThat(actual)
            .as("Verify CommunityModeratorAssistant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityModeratorAssistantUpdatableFieldsEquals(
        CommunityModeratorAssistant expected,
        CommunityModeratorAssistant actual
    ) {
        assertThat(actual)
            .as("Verify CommunityModeratorAssistant relevant properties")
            .satisfies(a -> assertThat(a.getCanManageGroups()).as("check canManageGroups").isEqualTo(expected.getCanManageGroups()))
            .satisfies(a -> assertThat(a.getCanReviewEvents()).as("check canReviewEvents").isEqualTo(expected.getCanReviewEvents()))
            .satisfies(a ->
                assertThat(a.getCanManageParticipants()).as("check canManageParticipants").isEqualTo(expected.getCanManageParticipants())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityModeratorAssistantUpdatableRelationshipsEquals(
        CommunityModeratorAssistant expected,
        CommunityModeratorAssistant actual
    ) {
        assertThat(actual)
            .as("Verify CommunityModeratorAssistant relationships")
            .satisfies(a -> assertThat(a.getCommunity()).as("check community").isEqualTo(expected.getCommunity()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
