package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAllPropertiesEquals(Community expected, Community actual) {
        assertCommunityAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAllUpdatablePropertiesEquals(Community expected, Community actual) {
        assertCommunityUpdatableFieldsEquals(expected, actual);
        assertCommunityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityAutoGeneratedPropertiesEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityUpdatableFieldsEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getVisibility()).as("check visibility").isEqualTo(expected.getVisibility()))
            .satisfies(a -> assertThat(a.getCoverImageUrl()).as("check coverImageUrl").isEqualTo(expected.getCoverImageUrl()))
            .satisfies(a -> assertThat(a.getCommunityType()).as("check communityType").isEqualTo(expected.getCommunityType()))
            .satisfies(a -> assertThat(a.getPartnerTrustLevel()).as("check partnerTrustLevel").isEqualTo(expected.getPartnerTrustLevel()))
            .satisfies(a -> assertThat(a.getIsVerifiedPartner()).as("check isVerifiedPartner").isEqualTo(expected.getIsVerifiedPartner()))
            .satisfies(a -> assertThat(a.getIsDiscoverable()).as("check isDiscoverable").isEqualTo(expected.getIsDiscoverable()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunityUpdatableRelationshipsEquals(Community expected, Community actual) {
        assertThat(actual)
            .as("Verify Community relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()))
            .satisfies(a -> assertThat(a.getCategoryHub()).as("check categoryHub").isEqualTo(expected.getCategoryHub()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLeadModerator()).as("check leadModerator").isEqualTo(expected.getLeadModerator()));
    }
}
