package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventParticipantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventParticipantAllPropertiesEquals(EventParticipant expected, EventParticipant actual) {
        assertEventParticipantAutoGeneratedPropertiesEquals(expected, actual);
        assertEventParticipantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventParticipantAllUpdatablePropertiesEquals(EventParticipant expected, EventParticipant actual) {
        assertEventParticipantUpdatableFieldsEquals(expected, actual);
        assertEventParticipantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventParticipantAutoGeneratedPropertiesEquals(EventParticipant expected, EventParticipant actual) {
        assertThat(actual)
            .as("Verify EventParticipant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventParticipantUpdatableFieldsEquals(EventParticipant expected, EventParticipant actual) {
        assertThat(actual)
            .as("Verify EventParticipant relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventParticipantUpdatableRelationshipsEquals(EventParticipant expected, EventParticipant actual) {
        assertThat(actual)
            .as("Verify EventParticipant relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
