package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventMessageAllPropertiesEquals(EventMessage expected, EventMessage actual) {
        assertEventMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertEventMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventMessageAllUpdatablePropertiesEquals(EventMessage expected, EventMessage actual) {
        assertEventMessageUpdatableFieldsEquals(expected, actual);
        assertEventMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventMessageAutoGeneratedPropertiesEquals(EventMessage expected, EventMessage actual) {
        assertThat(actual)
            .as("Verify EventMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventMessageUpdatableFieldsEquals(EventMessage expected, EventMessage actual) {
        assertThat(actual)
            .as("Verify EventMessage relevant properties")
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getModerationStatus()).as("check moderationStatus").isEqualTo(expected.getModerationStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventMessageUpdatableRelationshipsEquals(EventMessage expected, EventMessage actual) {
        assertThat(actual)
            .as("Verify EventMessage relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()));
    }
}
