package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventRatingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRatingAllPropertiesEquals(EventRating expected, EventRating actual) {
        assertEventRatingAutoGeneratedPropertiesEquals(expected, actual);
        assertEventRatingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRatingAllUpdatablePropertiesEquals(EventRating expected, EventRating actual) {
        assertEventRatingUpdatableFieldsEquals(expected, actual);
        assertEventRatingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRatingAutoGeneratedPropertiesEquals(EventRating expected, EventRating actual) {
        assertThat(actual)
            .as("Verify EventRating auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRatingUpdatableFieldsEquals(EventRating expected, EventRating actual) {
        assertThat(actual)
            .as("Verify EventRating relevant properties")
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getReviewText()).as("check reviewText").isEqualTo(expected.getReviewText()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventRatingUpdatableRelationshipsEquals(EventRating expected, EventRating actual) {
        assertThat(actual)
            .as("Verify EventRating relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
