package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FollowRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowRequestAllPropertiesEquals(FollowRequest expected, FollowRequest actual) {
        assertFollowRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertFollowRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowRequestAllUpdatablePropertiesEquals(FollowRequest expected, FollowRequest actual) {
        assertFollowRequestUpdatableFieldsEquals(expected, actual);
        assertFollowRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowRequestAutoGeneratedPropertiesEquals(FollowRequest expected, FollowRequest actual) {
        assertThat(actual)
            .as("Verify FollowRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowRequestUpdatableFieldsEquals(FollowRequest expected, FollowRequest actual) {
        assertThat(actual)
            .as("Verify FollowRequest relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowRequestUpdatableRelationshipsEquals(FollowRequest expected, FollowRequest actual) {
        assertThat(actual)
            .as("Verify FollowRequest relationships")
            .satisfies(a -> assertThat(a.getRequester()).as("check requester").isEqualTo(expected.getRequester()))
            .satisfies(a -> assertThat(a.getTargetUser()).as("check targetUser").isEqualTo(expected.getTargetUser()));
    }
}
