package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HonorBadgeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHonorBadgeAllPropertiesEquals(HonorBadge expected, HonorBadge actual) {
        assertHonorBadgeAutoGeneratedPropertiesEquals(expected, actual);
        assertHonorBadgeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHonorBadgeAllUpdatablePropertiesEquals(HonorBadge expected, HonorBadge actual) {
        assertHonorBadgeUpdatableFieldsEquals(expected, actual);
        assertHonorBadgeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHonorBadgeAutoGeneratedPropertiesEquals(HonorBadge expected, HonorBadge actual) {
        assertThat(actual)
            .as("Verify HonorBadge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHonorBadgeUpdatableFieldsEquals(HonorBadge expected, HonorBadge actual) {
        assertThat(actual)
            .as("Verify HonorBadge relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNameTemplate()).as("check nameTemplate").isEqualTo(expected.getNameTemplate()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getBadgeType()).as("check badgeType").isEqualTo(expected.getBadgeType()))
            .satisfies(a -> assertThat(a.getMinimumCheckIns()).as("check minimumCheckIns").isEqualTo(expected.getMinimumCheckIns()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHonorBadgeUpdatableRelationshipsEquals(HonorBadge expected, HonorBadge actual) {
        assertThat(actual)
            .as("Verify HonorBadge relationships")
            .satisfies(a -> assertThat(a.getCommunity()).as("check community").isEqualTo(expected.getCommunity()));
    }
}
