package com.bialem.backend.domain;

import static com.bialem.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PartnerOfferRedemptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferRedemptionAllPropertiesEquals(PartnerOfferRedemption expected, PartnerOfferRedemption actual) {
        assertPartnerOfferRedemptionAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerOfferRedemptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferRedemptionAllUpdatablePropertiesEquals(
        PartnerOfferRedemption expected,
        PartnerOfferRedemption actual
    ) {
        assertPartnerOfferRedemptionUpdatableFieldsEquals(expected, actual);
        assertPartnerOfferRedemptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferRedemptionAutoGeneratedPropertiesEquals(
        PartnerOfferRedemption expected,
        PartnerOfferRedemption actual
    ) {
        assertThat(actual)
            .as("Verify PartnerOfferRedemption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferRedemptionUpdatableFieldsEquals(PartnerOfferRedemption expected, PartnerOfferRedemption actual) {
        assertThat(actual)
            .as("Verify PartnerOfferRedemption relevant properties")
            .satisfies(a -> assertThat(a.getToken()).as("check token").isEqualTo(expected.getToken()))
            .satisfies(a -> assertThat(a.getRedemptionCode()).as("check redemptionCode").isEqualTo(expected.getRedemptionCode()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIssuedAt()).as("check issuedAt").isEqualTo(expected.getIssuedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()))
            .satisfies(a -> assertThat(a.getRedeemedAt()).as("check redeemedAt").isEqualTo(expected.getRedeemedAt()))
            .satisfies(a ->
                assertThat(a.getOrderAmount())
                    .as("check orderAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOrderAmount())
            )
            .satisfies(a ->
                assertThat(a.getDiscountAmount())
                    .as("check discountAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferRedemptionUpdatableRelationshipsEquals(
        PartnerOfferRedemption expected,
        PartnerOfferRedemption actual
    ) {
        assertThat(actual)
            .as("Verify PartnerOfferRedemption relationships")
            .satisfies(a -> assertThat(a.getOffer()).as("check offer").isEqualTo(expected.getOffer()))
            .satisfies(a -> assertThat(a.getVenue()).as("check venue").isEqualTo(expected.getVenue()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getRedeemedBy()).as("check redeemedBy").isEqualTo(expected.getRedeemedBy()));
    }
}
