package com.bialem.backend.domain;

import static com.bialem.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PartnerOfferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferAllPropertiesEquals(PartnerOffer expected, PartnerOffer actual) {
        assertPartnerOfferAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerOfferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferAllUpdatablePropertiesEquals(PartnerOffer expected, PartnerOffer actual) {
        assertPartnerOfferUpdatableFieldsEquals(expected, actual);
        assertPartnerOfferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferAutoGeneratedPropertiesEquals(PartnerOffer expected, PartnerOffer actual) {
        assertThat(actual)
            .as("Verify PartnerOffer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferUpdatableFieldsEquals(PartnerOffer expected, PartnerOffer actual) {
        assertThat(actual)
            .as("Verify PartnerOffer relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getDiscountPercent())
                    .as("check discountPercent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountPercent())
            )
            .satisfies(a ->
                assertThat(a.getMinimumSpend())
                    .as("check minimumSpend")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinimumSpend())
            )
            .satisfies(a ->
                assertThat(a.getMaximumDiscount())
                    .as("check maximumDiscount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaximumDiscount())
            )
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidUntil()).as("check validUntil").isEqualTo(expected.getValidUntil()))
            .satisfies(a -> assertThat(a.getValidDays()).as("check validDays").isEqualTo(expected.getValidDays()))
            .satisfies(a -> assertThat(a.getDailyStartTime()).as("check dailyStartTime").isEqualTo(expected.getDailyStartTime()))
            .satisfies(a -> assertThat(a.getDailyEndTime()).as("check dailyEndTime").isEqualTo(expected.getDailyEndTime()))
            .satisfies(a -> assertThat(a.getPerUserLimit()).as("check perUserLimit").isEqualTo(expected.getPerUserLimit()))
            .satisfies(a -> assertThat(a.getTerms()).as("check terms").isEqualTo(expected.getTerms()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerOfferUpdatableRelationshipsEquals(PartnerOffer expected, PartnerOffer actual) {
        assertThat(actual)
            .as("Verify PartnerOffer relationships")
            .satisfies(a -> assertThat(a.getVenue()).as("check venue").isEqualTo(expected.getVenue()));
    }
}
