package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartnerVenueStaffAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerVenueStaffAllPropertiesEquals(PartnerVenueStaff expected, PartnerVenueStaff actual) {
        assertPartnerVenueStaffAutoGeneratedPropertiesEquals(expected, actual);
        assertPartnerVenueStaffAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerVenueStaffAllUpdatablePropertiesEquals(PartnerVenueStaff expected, PartnerVenueStaff actual) {
        assertPartnerVenueStaffUpdatableFieldsEquals(expected, actual);
        assertPartnerVenueStaffUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerVenueStaffAutoGeneratedPropertiesEquals(PartnerVenueStaff expected, PartnerVenueStaff actual) {
        assertThat(actual)
            .as("Verify PartnerVenueStaff auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerVenueStaffUpdatableFieldsEquals(PartnerVenueStaff expected, PartnerVenueStaff actual) {
        assertThat(actual)
            .as("Verify PartnerVenueStaff relevant properties")
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartnerVenueStaffUpdatableRelationshipsEquals(PartnerVenueStaff expected, PartnerVenueStaff actual) {
        assertThat(actual)
            .as("Verify PartnerVenueStaff relationships")
            .satisfies(a -> assertThat(a.getVenue()).as("check venue").isEqualTo(expected.getVenue()))
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
