package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlatformTeamMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformTeamMemberAllPropertiesEquals(PlatformTeamMember expected, PlatformTeamMember actual) {
        assertPlatformTeamMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatformTeamMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformTeamMemberAllUpdatablePropertiesEquals(PlatformTeamMember expected, PlatformTeamMember actual) {
        assertPlatformTeamMemberUpdatableFieldsEquals(expected, actual);
        assertPlatformTeamMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformTeamMemberAutoGeneratedPropertiesEquals(PlatformTeamMember expected, PlatformTeamMember actual) {
        assertThat(actual)
            .as("Verify PlatformTeamMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformTeamMemberUpdatableFieldsEquals(PlatformTeamMember expected, PlatformTeamMember actual) {
        assertThat(actual)
            .as("Verify PlatformTeamMember relevant properties")
            .satisfies(a -> assertThat(a.getRoleCode()).as("check roleCode").isEqualTo(expected.getRoleCode()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformTeamMemberUpdatableRelationshipsEquals(PlatformTeamMember expected, PlatformTeamMember actual) {
        assertThat(actual)
            .as("Verify PlatformTeamMember relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getAssignedBy()).as("check assignedBy").isEqualTo(expected.getAssignedBy()));
    }
}
