package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PostMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMediaAllPropertiesEquals(PostMedia expected, PostMedia actual) {
        assertPostMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertPostMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMediaAllUpdatablePropertiesEquals(PostMedia expected, PostMedia actual) {
        assertPostMediaUpdatableFieldsEquals(expected, actual);
        assertPostMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMediaAutoGeneratedPropertiesEquals(PostMedia expected, PostMedia actual) {
        assertThat(actual)
            .as("Verify PostMedia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMediaUpdatableFieldsEquals(PostMedia expected, PostMedia actual) {
        assertThat(actual)
            .as("Verify PostMedia relevant properties")
            .satisfies(a -> assertThat(a.getMediaType()).as("check mediaType").isEqualTo(expected.getMediaType()))
            .satisfies(a -> assertThat(a.getStoragePath()).as("check storagePath").isEqualTo(expected.getStoragePath()))
            .satisfies(a -> assertThat(a.getSortOrder()).as("check sortOrder").isEqualTo(expected.getSortOrder()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPostMediaUpdatableRelationshipsEquals(PostMedia expected, PostMedia actual) {
        assertThat(actual)
            .as("Verify PostMedia relationships")
            .satisfies(a -> assertThat(a.getPost()).as("check post").isEqualTo(expected.getPost()));
    }
}
