package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PushTokenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPushTokenAllPropertiesEquals(PushToken expected, PushToken actual) {
        assertPushTokenAutoGeneratedPropertiesEquals(expected, actual);
        assertPushTokenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPushTokenAllUpdatablePropertiesEquals(PushToken expected, PushToken actual) {
        assertPushTokenUpdatableFieldsEquals(expected, actual);
        assertPushTokenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPushTokenAutoGeneratedPropertiesEquals(PushToken expected, PushToken actual) {
        assertThat(actual)
            .as("Verify PushToken auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPushTokenUpdatableFieldsEquals(PushToken expected, PushToken actual) {
        assertThat(actual)
            .as("Verify PushToken relevant properties")
            .satisfies(a -> assertThat(a.getDeviceToken()).as("check deviceToken").isEqualTo(expected.getDeviceToken()))
            .satisfies(a -> assertThat(a.getPlatform()).as("check platform").isEqualTo(expected.getPlatform()))
            .satisfies(a -> assertThat(a.getDeviceName()).as("check deviceName").isEqualTo(expected.getDeviceName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastSeenAt()).as("check lastSeenAt").isEqualTo(expected.getLastSeenAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPushTokenUpdatableRelationshipsEquals(PushToken expected, PushToken actual) {
        assertThat(actual)
            .as("Verify PushToken relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
