package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoleAsserts {

    public static void assertRoleAllPropertiesEquals(Role expected, Role actual) {
        assertRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertRoleAllUpdatablePropertiesEquals(Role expected, Role actual) {
        assertRoleUpdatableFieldsEquals(expected, actual);
        assertRoleUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertRoleAutoGeneratedPropertiesEquals(Role expected, Role actual) {
        assertThat(actual)
            .as("Verify Role auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertRoleUpdatableFieldsEquals(Role expected, Role actual) {
        assertThat(actual)
            .as("Verify Role relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    public static void assertRoleUpdatableRelationshipsEquals(Role expected, Role actual) {}
}
