package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryAllPropertiesEquals(Story expected, Story actual) {
        assertStoryAutoGeneratedPropertiesEquals(expected, actual);
        assertStoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryAllUpdatablePropertiesEquals(Story expected, Story actual) {
        assertStoryUpdatableFieldsEquals(expected, actual);
        assertStoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryAutoGeneratedPropertiesEquals(Story expected, Story actual) {
        assertThat(actual)
            .as("Verify Story auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryUpdatableFieldsEquals(Story expected, Story actual) {
        assertThat(actual)
            .as("Verify Story relevant properties")
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getMediaUrl()).as("check mediaUrl").isEqualTo(expected.getMediaUrl()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getShareWithFollowers()).as("check shareWithFollowers").isEqualTo(expected.getShareWithFollowers())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryUpdatableRelationshipsEquals(Story expected, Story actual) {
        assertThat(actual)
            .as("Verify Story relationships")
            .satisfies(a -> assertThat(a.getAuthor()).as("check author").isEqualTo(expected.getAuthor()));
    }
}
