package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StoryViewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryViewAllPropertiesEquals(StoryView expected, StoryView actual) {
        assertStoryViewAutoGeneratedPropertiesEquals(expected, actual);
        assertStoryViewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryViewAllUpdatablePropertiesEquals(StoryView expected, StoryView actual) {
        assertStoryViewUpdatableFieldsEquals(expected, actual);
        assertStoryViewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryViewAutoGeneratedPropertiesEquals(StoryView expected, StoryView actual) {
        assertThat(actual)
            .as("Verify StoryView auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryViewUpdatableFieldsEquals(StoryView expected, StoryView actual) {
        assertThat(actual)
            .as("Verify StoryView relevant properties")
            .satisfies(a -> assertThat(a.getViewedAt()).as("check viewedAt").isEqualTo(expected.getViewedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryViewUpdatableRelationshipsEquals(StoryView expected, StoryView actual) {
        assertThat(actual)
            .as("Verify StoryView relationships")
            .satisfies(a -> assertThat(a.getStory()).as("check story").isEqualTo(expected.getStory()))
            .satisfies(a -> assertThat(a.getViewer()).as("check viewer").isEqualTo(expected.getViewer()));
    }
}
