package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StoryCommunityTargetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryCommunityTargetAllPropertiesEquals(StoryCommunityTarget expected, StoryCommunityTarget actual) {
        assertStoryCommunityTargetAutoGeneratedPropertiesEquals(expected, actual);
        assertStoryCommunityTargetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryCommunityTargetAllUpdatablePropertiesEquals(StoryCommunityTarget expected, StoryCommunityTarget actual) {
        assertStoryCommunityTargetUpdatableFieldsEquals(expected, actual);
        assertStoryCommunityTargetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryCommunityTargetAutoGeneratedPropertiesEquals(StoryCommunityTarget expected, StoryCommunityTarget actual) {
        assertThat(actual)
            .as("Verify StoryCommunityTarget auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryCommunityTargetUpdatableFieldsEquals(StoryCommunityTarget expected, StoryCommunityTarget actual) {
        assertThat(actual)
            .as("Verify StoryCommunityTarget relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStoryCommunityTargetUpdatableRelationshipsEquals(StoryCommunityTarget expected, StoryCommunityTarget actual) {
        assertThat(actual)
            .as("Verify StoryCommunityTarget relationships")
            .satisfies(a -> assertThat(a.getStory()).as("check story").isEqualTo(expected.getStory()))
            .satisfies(a -> assertThat(a.getCommunity()).as("check community").isEqualTo(expected.getCommunity()));
    }
}
