package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserRoleAsserts {

    public static void assertUserRoleAllPropertiesEquals(UserRole expected, UserRole actual) {
        assertUserRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertUserRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    public static void assertUserRoleAllUpdatablePropertiesEquals(UserRole expected, UserRole actual) {
        assertUserRoleUpdatableFieldsEquals(expected, actual);
        assertUserRoleUpdatableRelationshipsEquals(expected, actual);
    }

    public static void assertUserRoleAutoGeneratedPropertiesEquals(UserRole expected, UserRole actual) {
        assertThat(actual)
            .as("Verify UserRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    public static void assertUserRoleUpdatableFieldsEquals(UserRole expected, UserRole actual) {
        assertThat(actual)
            .as("Verify UserRole relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    public static void assertUserRoleUpdatableRelationshipsEquals(UserRole expected, UserRole actual) {
        assertThat(actual)
            .as("Verify UserRole relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }
}
