package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserHonorBadgeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHonorBadgeAllPropertiesEquals(UserHonorBadge expected, UserHonorBadge actual) {
        assertUserHonorBadgeAutoGeneratedPropertiesEquals(expected, actual);
        assertUserHonorBadgeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHonorBadgeAllUpdatablePropertiesEquals(UserHonorBadge expected, UserHonorBadge actual) {
        assertUserHonorBadgeUpdatableFieldsEquals(expected, actual);
        assertUserHonorBadgeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHonorBadgeAutoGeneratedPropertiesEquals(UserHonorBadge expected, UserHonorBadge actual) {
        assertThat(actual)
            .as("Verify UserHonorBadge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHonorBadgeUpdatableFieldsEquals(UserHonorBadge expected, UserHonorBadge actual) {
        assertThat(actual)
            .as("Verify UserHonorBadge relevant properties")
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getAwardedAt()).as("check awardedAt").isEqualTo(expected.getAwardedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserHonorBadgeUpdatableRelationshipsEquals(UserHonorBadge expected, UserHonorBadge actual) {
        assertThat(actual)
            .as("Verify UserHonorBadge relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getBadge()).as("check badge").isEqualTo(expected.getBadge()))
            .satisfies(a -> assertThat(a.getAwardedBy()).as("check awardedBy").isEqualTo(expected.getAwardedBy()));
    }
}
