package com.bialem.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReviewAllPropertiesEquals(UserReview expected, UserReview actual) {
        assertUserReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertUserReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReviewAllUpdatablePropertiesEquals(UserReview expected, UserReview actual) {
        assertUserReviewUpdatableFieldsEquals(expected, actual);
        assertUserReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReviewAutoGeneratedPropertiesEquals(UserReview expected, UserReview actual) {
        assertThat(actual)
            .as("Verify UserReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReviewUpdatableFieldsEquals(UserReview expected, UserReview actual) {
        assertThat(actual)
            .as("Verify UserReview relevant properties")
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getReviewText()).as("check reviewText").isEqualTo(expected.getReviewText()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserReviewUpdatableRelationshipsEquals(UserReview expected, UserReview actual) {
        assertThat(actual)
            .as("Verify UserReview relationships")
            .satisfies(a -> assertThat(a.getReviewer()).as("check reviewer").isEqualTo(expected.getReviewer()))
            .satisfies(a -> assertThat(a.getReviewedUser()).as("check reviewedUser").isEqualTo(expected.getReviewedUser()))
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()));
    }
}
