package com.bialem.backend.domain.enumeration;

/**
 * Supported notification event types.
 */
public enum NotificationEventType {
    NEW_FOLLOWER,
    FOLLOW_REQUEST,
    FOLLOW_ACCEPTED,
    FOLLOW_REJECTED,
    COMMUNITY_JOIN_REQUEST,
    COMMUNITY_JOIN_APPROVED,
    COMMUNITY_JOIN_REJECTED,
    EVENT_JOIN_REQUEST,
    EVENT_JOIN_APPROVED,
    EVENT_JOIN_REJECTED,
    EVENT_UPDATED,
    EVENT_CANCELLED,
    EVENT_REMINDER,
    COMMENT,
    LIKE,
    MENTION,
    COMMUNITY_ANNOUNCEMENT,
    SYSTEM_NOTIFICATION,
    // Kept for backwards compatibility with already deployed templates/events.
    EVENT_PUBLISHED,
    COMMUNITY_MEMBERSHIP_REQUEST,
    COMMUNITY_MEMBERSHIP_APPROVED,
    COMMUNITY_MEMBERSHIP_REJECTED,
    HONOR_BADGE_AWARDED,
    USER_REVIEW,
    SYSTEM_ANNOUNCEMENT,
    ADMIN_BROADCAST,
    EVENT_START_REMINDER,
}
