import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { showAppAlert, showAppError } from "./AppAlert";
import { ImagePickerField } from "./ImagePickerField";
import { normalizeImageUrl } from "../lib/media-url";
import { type PickedImage, uploadCommunityCover, uploadEventCover } from "../lib/storage";
import { colors } from "../theme/colors";

export type SelectOption={value:string;label:string};
export type FormField={key:string;label:string;kind?:"text"|"multiline"|"number"|"datetime"|"boolean"|"select"|"image";required?:boolean;options?:SelectOption[]};
type Props<T extends Record<string,any>>={title:string;listRoute:string;empty:T;fields:FormField[];load:(id:number)=>Promise<T>;create:(value:T)=>Promise<T>;update:(id:number,value:T)=>Promise<T>;imageBucket?:"community-covers"|"event-covers"};

export function ManagementEntityForm<T extends Record<string,any>>({title,listRoute,empty,fields,load,create,update,imageBucket}:Props<T>){
 const{id:rawId}=useLocalSearchParams<{id:string}>();const router=useRouter();const creating=rawId==="new";const id=Number(rawId),valid=creating||(Number.isSafeInteger(id)&&id>0);
 const[value,setValue]=useState<T>(empty),[pickedImage,setPickedImage]=useState<PickedImage|null>(null),[loading,setLoading]=useState(!creating&&valid),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(valid?null:"Geçersiz kayıt kimliği.");
 const reload=async()=>{if(creating||!valid)return;setLoading(true);setError(null);try{setValue(await load(id));setPickedImage(null)}catch(e){setError(e instanceof Error?e.message:"Kayıt yüklenirken bir hata oluştu.")}finally{setLoading(false)}};
 useEffect(()=>{void reload()},[rawId]);
 const missing=useMemo(()=>fields.some(f=>f.required&&!String(value[f.key]??"").trim()),[fields,value]);
 const save=async()=>{if(missing)return void showAppError("Zorunlu alanları doldurun.");setSaving(true);try{let payload=value;if(pickedImage&&imageBucket){const owner=creating?`new-${Date.now()}`:String(id);const uploaded=imageBucket==="community-covers"?await uploadCommunityCover({userId:owner,image:pickedImage}):await uploadEventCover({userId:owner,image:pickedImage});payload={...value,coverImageUrl:uploaded.storagePath};}const saved=creating?await create(payload):await update(id,payload);setValue(saved);setPickedImage(null);await showAppAlert({title:"Kayıt kaydedildi.",icon:"success"});if(creating&&saved.id)router.replace(`${listRoute}/${saved.id}` as never)}catch(e){await showAppError(e instanceof Error?e.message:"Kayıt kaydedilemedi.")}finally{setSaving(false)}};
 return <><Stack.Screen options={{headerShown:true,title:creating?`${title} Oluştur`:`${title} Düzenle`}}/><ScrollView style={s.screen} contentContainerStyle={s.page}>{loading?<State><ActivityIndicator color={colors.accent}/><Text>Yükleniyor...</Text></State>:error?<State><Text style={s.error}>{error}</Text><Pressable style={s.button} onPress={()=>void reload()}><Text style={s.buttonText}>Tekrar dene</Text></Pressable><Pressable onPress={()=>router.replace(listRoute as never)}><Text style={s.link}>Yönetim ekranına dön</Text></Pressable></State>:<><Text style={s.title}>{creating?`Yeni ${title}`:(value.name??value.title??`#${id}`)}</Text>{fields.map(field=><View key={field.key} style={s.field}><Text style={s.label}>{field.label}{field.required?" *":""}</Text>{renderField(field,value,setValue,pickedImage,setPickedImage,saving)}</View>)}<Pressable disabled={saving} style={[s.button,saving&&s.disabled]} onPress={()=>void save()}>{saving?<ActivityIndicator color={colors.actionText}/>:<Text style={s.buttonText}>Kaydet</Text>}</Pressable></>}</ScrollView></>;
}
function renderField<T extends Record<string,any>>(field:FormField,value:T,setValue:(v:T)=>void,picked:PickedImage|null,setPicked:(v:PickedImage|null)=>void,disabled:boolean){
 if(field.kind==="boolean")return <Switch value={Boolean(value[field.key])} onValueChange={v=>setValue({...value,[field.key]:v})}/>;
 if(field.kind==="select")return <View style={s.options}>{field.options?.map(o=><Pressable key={o.value} accessibilityRole="radio" accessibilityState={{checked:value[field.key]===o.value}} onPress={()=>setValue({...value,[field.key]:o.value})} style={[s.option,value[field.key]===o.value&&s.optionSelected]}><Text style={[s.optionText,value[field.key]===o.value&&s.optionTextSelected]}>{o.label}</Text></Pressable>)}</View>;
 if(field.kind==="image")return <><>{value[field.key]&&!picked?<View style={s.preview}><Image source={{uri:normalizeImageUrl(String(value[field.key]))}} style={s.image} resizeMode="cover"/><Text numberOfLines={1} style={s.imageUrl}>{String(value[field.key])}</Text></View>:null}</><ImagePickerField label="Yeni kapak görseli" image={picked} onChange={setPicked} onError={m=>void showAppError(m)} disabled={disabled}/>{value[field.key]?<Pressable onPress={()=>{setValue({...value,[field.key]:null});setPicked(null)}}><Text style={s.remove}>Mevcut görseli kaldır</Text></Pressable>:null}</>;
 return <TextInput style={[s.input,field.kind==="multiline"&&s.multiline]} multiline={field.kind==="multiline"} value={toInput(value[field.key],field.kind)} keyboardType={field.kind==="number"?"numeric":"default"} onChangeText={text=>setValue({...value,[field.key]:fromInput(text,field.kind)})}/>;
}
function State({children}:{children:any}){return <View style={s.state}>{children}</View>};function toInput(v:any,kind?:string){if(v==null)return "";if(kind==="datetime"){const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,16)}return String(v)}function fromInput(v:string,kind?:string){if(kind==="number")return v===""?null:Number(v);if(kind==="datetime")return v&&!Number.isNaN(new Date(v).getTime())?new Date(v).toISOString():null;return v}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.page},page:{padding:16,paddingBottom:40,gap:14},title:{fontSize:25,fontWeight:"900",color:colors.ink},field:{gap:7},label:{fontSize:13,fontWeight:"800",color:colors.ink},input:{minHeight:48,paddingHorizontal:13,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.surface,color:colors.ink},multiline:{minHeight:110,paddingTop:12,textAlignVertical:"top"},options:{flexDirection:"row",flexWrap:"wrap",gap:8},option:{minHeight:42,justifyContent:"center",paddingHorizontal:14,borderRadius:12,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},optionSelected:{borderColor:colors.accent,backgroundColor:colors.accentSoft},optionText:{fontWeight:"700",color:colors.muted},optionTextSelected:{color:colors.ink,fontWeight:"900"},preview:{overflow:"hidden",borderRadius:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},image:{width:"100%",height:220},imageUrl:{padding:10,fontSize:11,color:colors.muted},remove:{color:colors.danger,fontWeight:"800"},button:{minHeight:50,alignItems:"center",justifyContent:"center",borderRadius:99,backgroundColor:colors.action},buttonText:{fontWeight:"900",color:colors.actionText},disabled:{opacity:.6},state:{minHeight:260,alignItems:"center",justifyContent:"center",gap:12},error:{color:colors.danger,fontWeight:"800",textAlign:"center"},link:{color:colors.accent,fontWeight:"800"}});
