import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { showAppAlert, showAppError } from "./AppAlert";
import { colors } from "../theme/colors";

export type FormField = { key:string; label:string; kind?:"text"|"multiline"|"number"|"datetime"|"boolean"; required?:boolean };
export function ManagementEntityForm<T extends Record<string, any>>({title,listRoute,empty,fields,load,create,update}:{title:string;listRoute:string;empty:T;fields:FormField[];load:(id:number)=>Promise<T>;create:(value:T)=>Promise<T>;update:(id:number,value:T)=>Promise<T>}) {
  const { id:rawId }=useLocalSearchParams<{id:string}>(); const router=useRouter(); const creating=rawId==="new";
  const id=Number(rawId), valid=creating||(Number.isSafeInteger(id)&&id>0);
  const [value,setValue]=useState<T>(empty),[loading,setLoading]=useState(!creating&&valid),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(valid?null:"Geçersiz kayıt kimliği.");
  const reload=async()=>{if(creating||!valid)return;setLoading(true);setError(null);try{setValue(await load(id));}catch(e){setError(e instanceof Error?e.message:"Kayıt yüklenirken bir hata oluştu.");}finally{setLoading(false)}};
  useEffect(()=>{void reload()},[rawId]);
  const missing=useMemo(()=>fields.some(f=>f.required&&!String(value[f.key]??"").trim()),[fields,value]);
  const save=async()=>{if(missing)return void showAppError("Zorunlu alanları doldurun.");setSaving(true);try{const saved=creating?await create(value):await update(id,value);setValue(saved);await showAppAlert({title:"Kayıt kaydedildi.",icon:"success"});if(creating&&saved.id)router.replace(`${listRoute}/${saved.id}` as never);}catch(e){await showAppError(e instanceof Error?e.message:"Kayıt kaydedilemedi.");}finally{setSaving(false)}};
  return <><Stack.Screen options={{headerShown:true,title:creating?`${title} Oluştur`:`${title} Düzenle`}}/><ScrollView style={s.screen} contentContainerStyle={s.page}>{loading?<View style={s.state}><ActivityIndicator color={colors.accent}/><Text>Yükleniyor...</Text></View>:error?<View style={s.state}><Text style={s.error}>{error}</Text><Pressable style={s.button} onPress={()=>void reload()}><Text style={s.buttonText}>Tekrar dene</Text></Pressable><Pressable onPress={()=>router.replace(listRoute as never)}><Text style={s.link}>Yönetim ekranına dön</Text></Pressable></View>:<><Text style={s.title}>{creating?`Yeni ${title}`:(value.name??value.title??`#${id}`)}</Text>{fields.map(field=><View key={field.key} style={s.field}><Text style={s.label}>{field.label}{field.required?" *":""}</Text>{field.kind==="boolean"?<Switch value={Boolean(value[field.key])} onValueChange={v=>setValue({...value,[field.key]:v})}/>:<TextInput style={[s.input,field.kind==="multiline"&&s.multiline]} multiline={field.kind==="multiline"} value={toInput(value[field.key],field.kind)} keyboardType={field.kind==="number"?"numeric":"default"} onChangeText={text=>setValue({...value,[field.key]:fromInput(text,field.kind)})}/>}</View>)}<Pressable disabled={saving} style={[s.button,saving&&{opacity:.6}]} onPress={()=>void save()}>{saving?<ActivityIndicator color={colors.actionText}/>:<Text style={s.buttonText}>Kaydet</Text>}</Pressable></>}</ScrollView></>;
}
function toInput(v:any,kind?:string){if(v==null)return "";if(kind==="datetime"){const d=new Date(v);if(Number.isNaN(d.getTime()))return "";return d.toISOString().slice(0,16)}return String(v)}
function fromInput(v:string,kind?:string){if(kind==="number")return v===""?null:Number(v);if(kind==="datetime")return v&&Number.isFinite(new Date(v).getTime())?new Date(v).toISOString():null;return v}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.page},page:{padding:16,paddingBottom:40,gap:12},title:{fontSize:25,fontWeight:"900",color:colors.ink},field:{gap:6},label:{fontSize:12,fontWeight:"800",color:colors.muted},input:{minHeight:48,paddingHorizontal:13,borderWidth:1,borderColor:colors.border,borderRadius:14,backgroundColor:colors.surface,color:colors.ink},multiline:{minHeight:110,paddingTop:12,textAlignVertical:"top"},button:{minHeight:50,alignItems:"center",justifyContent:"center",borderRadius:99,backgroundColor:colors.action},buttonText:{fontWeight:"900",color:colors.actionText},state:{minHeight:260,alignItems:"center",justifyContent:"center",gap:12},error:{color:colors.danger,fontWeight:"800",textAlign:"center"},link:{color:colors.accent,fontWeight:"800"}});
