import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { showAppAlert, showAppError } from "../../../src/components/AppAlert";
import { managementApi, type Community, type ManagedEvent, type ManagedUser, type ManagementNotification, type NotificationTargetType } from "../../../src/lib/management-api";
import { colors } from "../../../src/theme/colors";

const targets: Array<{ value: NotificationTargetType; label: string }> = [
  { value: "ALL_ACTIVE_USERS", label: "Tüm aktif kullanıcılar" }, { value: "SPECIFIC_USER", label: "Belirli kullanıcı" },
  { value: "ROLE", label: "Rol" }, { value: "COMMUNITY", label: "Topluluk" },
  { value: "EVENT_PARTICIPANTS", label: "Etkinlik katılımcıları" }, { value: "CITY", label: "Şehir" }
];

export default function ManagementNotificationDetail() {
  const { id: raw } = useLocalSearchParams<{ id: string }>(); const router = useRouter();
  const creating = raw === "new", id = Number(raw), valid = creating || (Number.isSafeInteger(id) && id > 0);
  const [item,setItem]=useState<ManagementNotification|null>(null),[loading,setLoading]=useState(!creating&&valid),[error,setError]=useState<string|null>(valid?null:"Geçersiz bildirim kimliği.");
  const [title,setTitle]=useState(""),[body,setBody]=useState(""),[route,setRoute]=useState(""),[targetType,setTargetType]=useState<NotificationTargetType>("ALL_ACTIVE_USERS"),[targetValue,setTargetValue]=useState(""),[push,setPush]=useState(true),[sending,setSending]=useState(false);
  const [users,setUsers]=useState<ManagedUser[]>([]),[communities,setCommunities]=useState<Community[]>([]),[events,setEvents]=useState<ManagedEvent[]>([]),[roles,setRoles]=useState<string[]>([]);
  const requestId=useRef(globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`);
  const load=async()=>{if(creating||!valid)return;setLoading(true);setError(null);try{setItem(await managementApi.notification(id))}catch(e){setError(e instanceof Error?e.message:"Bildirim yüklenemedi.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[raw]);
  useEffect(()=>{if(!creating)return;void Promise.all([managementApi.users(0,100),managementApi.communities(0,100),managementApi.events(0,100),managementApi.authorities()]).then(([u,c,e,a])=>{setUsers(u.filter(row=>row.activated));setCommunities(c);setEvents(e);setRoles(a.map(row=>row.name))}).catch(()=>undefined)},[creating]);
  const chooseTarget=(next:NotificationTargetType)=>{setTargetType(next);setTargetValue("")};
  const send=async()=>{if(!title.trim()||!body.trim())return void showAppError("Başlık ve mesaj zorunludur.");if(targetType!=="ALL_ACTIVE_USERS"&&!targetValue.trim())return void showAppError("Seçilen hedef için bir değer belirlemelisin.");const numeric=Number(targetValue);setSending(true);try{const summary=await managementApi.sendNotification({title:title.trim(),body:body.trim(),targetType,userId:targetType==="SPECIFIC_USER"?numeric:undefined,role:targetType==="ROLE"?targetValue:undefined,communityId:targetType==="COMMUNITY"?numeric:undefined,eventId:targetType==="EVENT_PARTICIPANTS"?numeric:undefined,city:targetType==="CITY"?targetValue.trim():undefined,notificationType:"SYSTEM",route:route.trim()||undefined,sendPush:push,inAppEnabled:true,scheduledAt:null,priority:"NORMAL",requestId:requestId.current});await showAppAlert({title:summary.status==="DUPLICATE"?"Bu bildirim daha önce kuyruğa alındı.":"Bildirim kuyruğa alındı.",text:`Alıcı: ${summary.recipientCount}\nPush uygun: ${summary.pushEligibleCount}\nPush tokenı olmayan: ${summary.withoutTokenCount}`,icon:"success"});router.replace("/management/notifications" as never)}catch(e){await showAppError(e instanceof Error?e.message:"Bildirim gönderilemedi.")}finally{setSending(false)}};
  const retry=async()=>{if(!item)return;try{await managementApi.retryNotification(item.id);await showAppAlert({title:"Yeni teslimat denemesi başlatıldı.",icon:"success"});void load()}catch(e){await showAppError(e instanceof Error?e.message:"Tekrar gönderilemedi.")}};
  return <><Stack.Screen options={{headerShown:true,title:creating?"Yeni Bildirim":"Bildirim Detayı"}}/><ScrollView style={s.screen} contentContainerStyle={s.page}>{creating?<><Field label="Başlık" value={title} set={setTitle}/><Field label="Mesaj" value={body} set={setBody} multiline/><Text style={s.label}>Hedef</Text><View style={s.choices}>{targets.map(target=><Choice key={target.value} label={target.label} active={targetType===target.value} onPress={()=>chooseTarget(target.value)}/>)}</View><TargetSelector type={targetType} value={targetValue} set={setTargetValue} users={users} communities={communities} events={events} roles={roles}/><Field label="Uygulama bağlantısı / rota" value={route} set={setRoute}/><View style={s.row}><Text style={s.label}>Firebase anlık bildirim gönder</Text><Switch value={push} onValueChange={setPush}/></View><Pressable disabled={sending} style={s.button} onPress={()=>void send()}>{sending?<ActivityIndicator color={colors.actionText}/>:<Text style={s.buttonText}>Bildirimi gönder</Text>}</Pressable></>:loading?<ActivityIndicator color={colors.accent}/>:error?<View style={s.state}><Text style={s.error}>{error}</Text><Pressable style={s.button} onPress={()=>void load()}><Text style={s.buttonText}>Tekrar dene</Text></Pressable></View>:item?<><Text style={s.title}>{item.title}</Text><Text style={s.body}>{item.body}</Text>{[["Bildirim türü",item.notificationType],["Kaynak",item.source],["Hedef",`Kullanıcı #${item.recipientUserId}`],["Firebase durumu",item.firebaseStatus],["Firebase ileti kimliği",item.firebaseMessageId||"Henüz yok"],["Başarılı push",item.pushSuccessful],["Başarısız push",item.pushFailed],["Deneme",item.attemptCount],["Oluşturulma",new Date(item.createdAt).toLocaleString("tr-TR")]].map(([key,value])=><View style={s.info} key={String(key)}><Text style={s.label}>{key}</Text><Text style={s.body}>{String(value)}</Text></View>)}{item.lastError?<Text style={s.error}>{item.lastError}</Text>:null}{["FAILED","PARTIAL"].includes(item.firebaseStatus)?<Pressable style={s.button} onPress={()=>void retry()}><Text style={s.buttonText}>Tekrar gönder</Text></Pressable>:null}</>:null}</ScrollView></>;
}

function TargetSelector({type,value,set,users,communities,events,roles}:{type:NotificationTargetType;value:string;set:(v:string)=>void;users:ManagedUser[];communities:Community[];events:ManagedEvent[];roles:string[]}){if(type==="ALL_ACTIVE_USERS")return <View style={s.notice}><Text style={s.body}>Bildirim tüm aktif hesaplara gönderilecek. Profil veya push tokenı zorunlu değildir.</Text></View>;if(type==="CITY")return <Field label="Şehir" value={value} set={set}/>;const options=type==="SPECIFIC_USER"?users.map(row=>({value:String(row.id),label:`${row.login} · #${row.id}`})):type==="COMMUNITY"?communities.filter(row=>row.id).map(row=>({value:String(row.id),label:row.name})):type==="EVENT_PARTICIPANTS"?events.filter(row=>row.id).map(row=>({value:String(row.id),label:row.title})):roles.map(role=>({value:role,label:role}));return <View style={s.field}><Text style={s.label}>Hedef seçimi</Text><View style={s.optionList}>{options.map(option=><Choice key={option.value} label={option.label} active={value===option.value} onPress={()=>set(option.value)}/>)}</View></View>}
function Choice({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.choice,active&&s.choiceActive]}><Text style={[s.choiceText,active&&s.choiceTextActive]}>{label}</Text></Pressable>}
function Field({label,value,set,multiline=false}:{label:string;value:string;set:(v:string)=>void;multiline?:boolean}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} multiline={multiline} style={[s.input,multiline&&s.textArea]}/></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.page},page:{padding:16,paddingBottom:40,gap:12},field:{gap:6},label:{fontSize:12,fontWeight:"900",color:colors.muted},input:{minHeight:48,padding:13,borderRadius:14,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,color:colors.ink},textArea:{minHeight:110,textAlignVertical:"top"},row:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",padding:12},button:{minHeight:50,alignItems:"center",justifyContent:"center",paddingHorizontal:18,borderRadius:99,backgroundColor:colors.action},buttonText:{fontWeight:"900",color:colors.actionText},title:{fontSize:25,fontWeight:"900",color:colors.ink},body:{color:colors.ink},info:{gap:3,padding:12,borderRadius:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},state:{minHeight:240,alignItems:"center",justifyContent:"center",gap:12},error:{color:colors.danger,fontWeight:"800"},choices:{flexDirection:"row",flexWrap:"wrap",gap:8},choice:{paddingHorizontal:12,paddingVertical:9,borderRadius:99,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},choiceActive:{borderColor:colors.accent,backgroundColor:colors.accentSoft},choiceText:{fontSize:12,fontWeight:"800",color:colors.ink},choiceTextActive:{color:colors.accent},optionList:{flexDirection:"row",flexWrap:"wrap",gap:8},notice:{padding:14,borderRadius:14,backgroundColor:colors.accentSoft}});
