import { Ionicons } from "@expo/vector-icons";
import { useCallback, useState } from "react";
import { AgendaCalendar, type AgendaPlan } from "../../src/components/AgendaCalendar";
import { api } from "../../src/lib/api";
import { colors } from "../../src/theme/colors";

type CalendarItem={type:"BIALEM_EVENT"|"CITY_EVENT"|"BIRTHDAY";referenceId:string;title:string;description:string|null;date:string;startsAt:string|null;endsAt:string|null;imageUrl:string|null;location:string|null;category:string|null;priceLabel:string|null;route:string;participantCount:number|null;username:string|null;calculatedAge:number|null};
type Response={counts:{bialemEvents:number;cityEvents:number;birthdays:number;total:number};items:CalendarItem[];upcoming:CalendarItem[]};
export default function CalendarScreen(){
 const [plans,setPlans]=useState<AgendaPlan[]>([]),[counts,setCounts]=useState({bialemEvents:0,cityEvents:0,birthdays:0,total:0}),[upcoming,setUpcoming]=useState<CalendarItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async(start:string,end:string)=>{setLoading(true);setError(null);const startDate=start.slice(0,10),endDate=new Date(new Date(end).getTime()-86400000).toISOString().slice(0,10);try{const data=await api.rest.get<Response>(`/api/app/calendar?startDate=${startDate}&endDate=${endDate}`);setCounts(data.counts);setUpcoming(data.upcoming);setPlans(data.items.map(i=>({event_id:`${i.type}:${i.referenceId}`,title:i.title,starts_at:i.startsAt||`${i.date}T12:00:00`,ends_at:i.endsAt,location_name:i.location,event_status:"published",participation_status:i.type==="BIRTHDAY"?"birthday":"discovery",community_name:i.category||typeLabel(i.type),event_type:i.type,source:"community",route:i.route,description:i.description,image_url:i.imageUrl,price_label:i.priceLabel,username:i.username,calculated_age:i.calculatedAge})));}catch(e){setError(e instanceof Error?e.message:"Takvim yüklenemedi");}finally{setLoading(false);}},[]);
 return <main className="planner-page"><section className="planner-intro"><div className="planner-intro-icon"><Ionicons name="calendar" size={20} color="#fff"/></div><div className="planner-intro-copy"><small className="planner-kicker">BİALEM GENEL TAKVİM</small><h1 className="planner-heading">Şehrinde neler var?</h1><p className="planner-description">Bialem etkinlikleri, şehir keşifleri ve doğum günleri tek takvimde.</p></div></section>
 <section className="calendar-counts"><span>Bialem Etkinlikleri <b>{counts.bialemEvents}</b></span><span>Şehir Etkinlikleri <b>{counts.cityEvents}</b></span><span>Doğum Günleri <b>{counts.birthdays}</b></span></section>
 {error?<section className="planner-state planner-error-state"><Ionicons name="cloud-offline-outline" size={30} color={colors.danger}/><h2 className="planner-state-title">Takvim yüklenemedi</h2><p className="planner-state-copy">{error}</p></section>:<><AgendaCalendar plans={plans} onRangeChange={load}/>{loading?<div className="planner-refresh-pill"><i className="planner-pulse"/><span>Takvim güncelleniyor</span></div>:null}</>}
 {upcoming.length?<section className="planner-upcoming"><h2 className="planner-section-title">Yaklaşanlar</h2><div className="calendar-upcoming-scroll">{upcoming.map(i=><button key={`${i.type}:${i.referenceId}`} className="calendar-upcoming-card" onClick={()=>location.assign(i.route)}>{i.imageUrl?<img src={i.imageUrl} alt=""/>:<span className="calendar-upcoming-fallback"><Ionicons name={i.type==="CITY_EVENT"?"location":"calendar"} size={24} color={colors.accent}/></span>}<small>{typeLabel(i.type)} · {relative(i.startsAt)}</small><strong>{i.title}</strong><span>{i.location||i.category||"Detayları görüntüle"}</span></button>)}</div></section>:null}</main>;
}
function typeLabel(t:CalendarItem["type"]){return t==="CITY_EVENT"?"Şehir Etkinliği":t==="BIRTHDAY"?"Doğum Günü":"Bialem Etkinliği"} function relative(v:string|null){if(!v)return "";const d=Math.ceil((Date.parse(v)-Date.now())/86400000);return d<=0?"Bugün":d===1?"Yarın":`${d} gün sonra`}
